insert into article(title,body) values('Le constat : ça chauffe pour la planète !','Si l’on étudie le graphique des températures de la surface de la Terre au cours des 100 dernières années, on observe une augmentation d’environ 0,8 °C, principalement visible au cours des 30 dernières années. Les projections à partir de modèles climatiques ont été résumées lors du quatrième rapport du GIEC en 2007. Elles indiquent que la température mondiale continuera probablement d’augmenter au cours du XXIème siècle. Une augmentation comprise entre 1,1 °C et 2.9 °C, pour le scénario le plus optimiste, et entre 2.4 °C et 6.4 °C si les émissions sont plus élevées.La température terrestre mondiale se réchauffe depuis 1880. Une grande partie du réchauffement climatique a eu lieu à partir de 1970, et les 10 années les plus chaudes ont été enregistrées au cours des 12 dernières années.La montée en température devrait être supérieure au niveau des pôles, en particulier dans l’Arctique, où le recul des glaciers est largement observé. Mais ce n’est pas la seule preuve que nous sommes en train de vivre un réchauffement climatique rapide…');
insert into article(title,body) values('L’élévation du niveau de la mer','Le niveau global de la mer a augmenté de 17 centimètres au cours du XXe siècle. L’élévation durant la dernière décennie est presque deux fois supérieure à celle du siècle dernier…');
insert into article(title,body) values('Le réchauffement des océans','Les 700 premiers mètres des océans montrent une augmentation de 0,302 degrés Fahrenheit depuis 1969');
insert into article(title,body) values('La diminution des glaciers','Les plaques de glace du Groenland et de l’Antarctique diminuent, tout comme l’étendue et l’épaisseur de la banquise, et le phénomène va en s’accélérant…le recul des glaciers est visible dans le monde entier, :dans les Alpes,dans l’Himalaya,dans les Andes,en Alaska,en Afrique…');
insert into article(title,body) values('Les événements météorologiques extrêmes','Les situations de chaleur extrême ont augmenté tandis que les périodes de froid ont diminué depuis 1950. Sans compter les violentes tempêtes, les inondations…');
insert into article(title,body) values('Réchauffement climatique : l’Homme en cause…','La température moyenne de la planète dépend d’un processus atmosphérique délicat, basé sur l’équilibre de certains composés gazeux. L’augmentation significative de l’un de ces gaz dans l’atmosphère conduirait à un changement significatif dans l’équilibre climatique et donc de la température de la planète. Mais quelles sont les origines d’un tel phénomène ?');
insert into article(title,body) values('L’effet de serre','Pour beaucoup, l’effet de serre est un concept nouveau voire inconnu, mais les scientifiques, toutes disciplines confondues, ont commencé à l’étudier dès les années 1800.L’effet de serre est un processus de changement thermique ou d’augmentation de la température sur la planète produit par le flux de rayonnement solaire à travers notre atmosphère.En règle générale, ce type de radiation traverse l’atmosphère et atteint la terre où il libère une certaine quantité d’énergie qui, à son tour, génère de la chaleur. Ce même rayonnement retourne dans l’atmosphère pour se perdre dans l’espace. Ce processus maintient la température moyenne de la planète et est un phénomène naturel nécessaire.Cependant, avec l’accumulation des différents types de gaz (CO2, H2O, CH4, O3, CFC, NOx…), connus comme gaz à effet de serre, ce procédé d’entrée et de sortie du rayonnement solaire est modifié. L’activité humaine a contribué de manière significative à cette augmentation de l’effet de serre, notamment dans l’industrie, l’agriculture et au cours de l’expansion des centres urbains par le biais de la déforestation.');
insert into article(title,body) values('Les combustibles fossiles','Les combustibles fossiles sont ceux qui résultent de la décomposition de matière organique pendant des milliers d’années, et dont la combustion génère de grandes quantités d’énergie. Ce sont principalement :l’huile et tous ses dérivés (essence, gazole, diesel, kérosène),le charbon,le gaz naturel (principalement du méthane),le gaz liquide de pétrole (propane, butane).Ces combustibles sont la pierre angulaire du développement de l’activité humaine. Cependant, ce développement a un coût car l’utilisation de ces carburants libère de grandes émissions de gaz à effet de serre, principalement du CO2 et du CH4.');
insert into article(title,body) values('','');
insert into article(title,body) values('','');
insert into article(title,body) values('','');


